export const dbBooks = [
  {
    _id: "602c21b15d93e82af8a47352",
    stars: 2,
    key: "23",
    author: {
      name: "Charles",
      lastName: "Dickens",
    },
    title: "Samotnia /Pustkowie",
    list: {
      bbc: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4818148/samotnia-tom-1",
    page: 655,
    readed: false,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a47351",
    stars: 5,
    key: "22",
    author: {
      name: "F Scott",
      lastName: "Fitzgerald",
    },
    title: "Wielki Gatsby",
    list: {
      bbc: true,
      emp: true,
      gan: true,
      ama: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/178236/wielki-gatsby",
    page: 200,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a47354",
    stars: 3,
    key: "25",
    author: {
      name: "Douglas",
      lastName: "Adams",
    },
    title: "Autostopem przez Galaktykę",
    list: {
      bbc: true,
      gan: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/3708438/autostopem-przez-galaktyke",
    page: 322,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a4736b",
    stars: 3,
    key: "48",
    author: {
      name: "Margaret",
      lastName: "Atwood",
    },
    title: "Opowieść podręcznej",
    list: {
      bbc: true,
      ama: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4913859/opowiesc-podrecznej",
    page: 368,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a47397",
    stars: 4,
    key: "92",
    author: {
      name: "Antoine",
      lastName: "De Saint-Exupery",
    },
    title: "Mały Książę",
    list: {
      bbc: true,
      gan: true,
      ama: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4855903/maly-ksiaze",
    page: 112,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a473a8",
    stars: 2,
    key: "109",
    author: {
      name: "Heinrich",
      lastName: "Böll",
    },
    title: "Utracona cześć Katarzyny Blum",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/55311/utracona-czesc-katarzyny-blum-albo-jak-powstaje-przemoc-i-do-czego-moze-doprowadzic",
    page: 119,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a473c0",
    stars: 2,
    key: "133",
    author: {
      name: "Ernest",
      lastName: "Hemingway",
    },
    title: "Opowiadania",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/75490/opowiadania",
    page: 272,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a473c6",
    stars: 2,
    key: "139",
    author: {
      name: "Tove",
      lastName: "Jansson",
    },
    title: "Kometa nad Doliną Muminków",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4914003/kometa-nad-dolina-muminkow",
    page: 192,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a473d3",
    stars: 3,
    key: "152",
    author: {
      name: "Howard Phillips",
      lastName: "Lovecraft",
    },
    title: "Zew Cthulhu",
    list: {
      emp: true,
      gan: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/20696/zew-cthulhu",
    page: 308,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a473f3",
    stars: 2,
    key: "184",
    author: {
      name: "Sigrid",
      lastName: "Undset",
    },
    title: "Krystyna córka Lavransa",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/50479/krystyna-corka-lavransa-t-1-wianek",
    page: 254,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a473ff",
    stars: 1,
    key: "196",
    author: {
      name: "Borys",
      lastName: "Pasternak",
    },
    title: "Doktor Żywago",
    list: {
      gan: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4013342/doktor-zywago",
    page: 592,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a47408",
    stars: 1,
    key: "205",
    author: {
      name: "Nikos",
      lastName: "Kazantzakis",
    },
    title: "Grek Zorba",
    list: {
      gan: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/213944/grek-zorba",
    page: 320,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a47419",
    stars: 2,
    key: "222",
    author: {
      name: "Stieg",
      lastName: "Larsson",
    },
    title: "Mężczyźni, którzy nienawidzą kobiet",
    list: {
      gan: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/27644/mezczyzni-ktorzy-nienawidza-kobiet",
    page: 640,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a47421",
    stars: 1,
    key: "230",
    author: {
      name: "Adam",
      lastName: "Mickiewicz",
    },
    title: "Pan Tadeusz",
    list: {
      gan: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4936657/pan-tadeusz",
    page: 344,
    readed: true,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a4743d",
    stars: 1,
    key: "258",
    author: {
      name: "Rick",
      lastName: "Riordan",
    },
    title: "Percy Jackson i bogowie olimpijscy (seria)",
    list: {
      ama: true,
    },
    link: "https://lubimyczytac.pl/seria/13940/percy-jackson-and-the-olympians",
    page: 1792,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a47459",
    stars: 1,
    key: "286",
    author: {
      name: "Lawrence",
      lastName: "Wright",
    },
    title: "Wyniosłe wieże. Al-Kaida i atak na Amerykę",
    list: {
      ama: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4821335/wyniosle-wieze-al-kaida-i-atak-na-ameryke",
    page: 640,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a4745b",
    stars: 1,
    key: "288",
    author: {
      name: "Doris",
      lastName: "Kearns Goodwin",
    },
    title: "Team of Rivals: The Political Genius of Abraham Lincoln",
    list: {
      ama: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/24539/team-of-rivals-the-political-genius-of-abraham-lincoln",
    page: 916,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a47357",
    stars: 3,
    key: "28",
    author: {
      name: "John",
      lastName: "Steinbeck",
    },
    title: "Grona gniewu",
    list: {
      bbc: true,
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/141742/grona-gniewu",
    page: 672,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a4735f",
    stars: 1,
    key: "36",
    author: {
      name: "C.S.",
      lastName: "Lewis",
    },
    title: "Lew, Czarownica i Stara szafa",
    list: {
      bbc: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/91987/opowiesci-z-narnii",
    page: 886,
    readed: false,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a47377",
    stars: 1,
    key: "60",
    author: {
      name: "Gabriel Garcia",
      lastName: "Marquez",
    },
    title: "Miłość w czasach zarazy",
    list: {
      bbc: true,
      ama: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4628118/sto-lat-samotnosci",
    page: 456,
    readed: false,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a47396",
    stars: 2,
    key: "91",
    author: {
      name: "Joseph",
      lastName: "Conrad",
    },
    title: "Jądro ciemności",
    list: {
      bbc: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/262117/jadro-ciemnosci",
    page: 160,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a4739e",
    stars: 3,
    key: "99",
    author: {
      name: "Roald",
      lastName: "Dahl",
    },
    title: "Charlie i fabryka czekolady",
    list: {
      bbc: true,
      ama: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4909642/charlie-i-fabryka-czekolady",
    page: 256,
    readed: false,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a473b0",
    stars: 2,
    key: "117",
    author: {
      name: "Henryk",
      lastName: "Dasko",
    },
    title: "Odlot malowanego ptaka",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/25844/odlot-malowanego-ptaka",
    page: 252,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a473ba",
    stars: 2,
    key: "127",
    author: {
      name: "Romain",
      lastName: "Gary",
    },
    title: "Życie przed sobą",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/199789/zycie-przed-soba",
    page: 178,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a473c7",
    stars: 2,
    key: "140",
    author: {
      name: "Ernst",
      lastName: "Junger",
    },
    title: "Na marmurowych skałach",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/94102/na-marmurowych-skalach",
    page: 165,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a473cd",
    stars: 2,
    key: "146",
    author: {
      name: "Tadeusz",
      lastName: "Konwicki",
    },
    title: "Kalendarz i klepsydra",
    list: {
      emp: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4918201/kalendarz-i-klepsydra",
    page: 480,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a473f6",
    stars: 4,
    key: "187",
    author: {
      name: "Kurt",
      lastName: "Vonnegut",
    },
    title: "Rzeźnia numer pięć",
    list: {
      emp: true,
      gan: true,
      ama: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4866215/rzeznia-numer-piec",
    page: 240,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a47400",
    stars: 1,
    key: "197",
    author: {
      name: "Miguel de",
      lastName: "Cervantes",
    },
    title: "Don Kichot",
    list: {
      gan: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4913768/don-kichot-z-manczy",
    page: 204,
    readed: true,
    available: true,
  },
  {
    _id: "602c21b15d93e82af8a47416",
    stars: 1,
    key: "219",
    author: {
      name: "Anthony",
      lastName: "Burgess",
    },
    title: "Mechaniczna pomarańcza",
    list: {
      gan: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/5594/mechaniczna-pomarancza",
    page: 254,
    readed: false,
    available: false,
  },
  {
    _id: "602c21b15d93e82af8a4734b",
    stars: 2,
    key: "16",
    author: {
      name: "JRR",
      lastName: "Tolkien",
    },
    title: "Hobbit",
    list: {
      bbc: true,
      pozy: true,
    },
    link: "https://lubimyczytac.pl/ksiazka/4821058/hobbit",
    page: 304,
    readed: true,
    available: true,
  },
];
